In [1]:
import numpy as np

In [6]:
zeros = np.zeros((2,5))
empties = np.empty((2,5))
print zeros.dtype
print empties.dtype

float64
float64


# Compare ndarray "view" and python list

In [9]:
pythonlist = [1,2,3,4]
part_pythonlist = pythonlist[1:3]
print part_pythonlist
part_pythonlist[0] = 100
print part_pythonlist
print pythonlist

[2, 3]
[100, 3]
[1, 2, 3, 4]


In [10]:
a = np.array(pythonlist)
part_a = a[1:3]
print part_a
part_a[0]=100
print part_a
print a

[2 3]
[100   3]
[  1 100   3   4]


In [11]:
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
array3d.shape

(2, 2, 3)

In [15]:
array3d[0,:,1]

array([2, 5])

In [16]:
array3d[0,0,:]

array([1, 2, 3])

In [ ]:
array